[package]
name = "bugi_laco"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dxf = "0.5.0"
iced = {version = "0.9", features = ["canvas"]}
spacemath = { path = "../spacemath", version = "0.1.0" }